---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: capbm-controller-manager
  name: capbm-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capbm-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default